### ISSUE TITLE
bash3.2 n#: command not found

### ISSUE THREAD

**Issue by nowendwell** [tightenco/lambo#67]
Whenever I run lambo new-project the command always fails after running the `after` script. I get a command not found. I believe this has to do with the $SHELL command on line 395. $SHELL isn't defined anywhere in the preceeding code so i'm not exactly sure what it is trying to reference here.

```
if [[ "$SHELL" != "" ]]; then 
    exec "$SHELL"
```

When I comment out that if block, it runs to completion.

Config
```
#!/usr/bin/env bash

PROJECTPATH="./repos"
MESSAGE="Initial commit."
DEVELOP=false
AUTH=true
NODE=true
CODEEDITOR="atom"
BROWSER=""
LINK=true
DB_USERNAME="root"
DB_PASSWORD=""
```

After
```
#!/usr/bin/env bash

cd $PROJECTPATH/$PROJECTNAME
php artisan storage:link
```

**Comment by mattstauffer** [comment]
@nowendwell What's your OS? `$SHELL` is defined by default in the shell on macOS, so that's what I'm writing it against.

**Comment by nowendwell** [comment]
@mattstauffer It is MacOS High Sierra 10.13.6 using the default shell.

**Comment by mattstauffer** [comment]
@nowendwell huh. If you go to your terminal and type this, what do you get?

```bash
echo $SHELL
```

**Comment by nowendwell** [comment]
@mattstauffer I get `/bin/bash`

![screen shot 2019-03-04 at 11 35 49 am](https://user-images.githubusercontent.com/5315824/53757893-af9c6680-3e71-11e9-9d49-d7a5f6ce9b30.png)

**Comment by mattstauffer** [comment]
OK, then it's probably not having trouble finding `$SHELL`.

Do you get that error if you get rid of your after script?

**Comment by mattstauffer** [comment]
@nowendwell Apologies--I apparently didn't see your response and just let it die. Are you still having this problem?

**Comment by nowendwell** [comment]
No worries. Yeah I'm still having it. I just end up closing the terminal
and opening a new one.

**Comment by mattstauffer** [comment]
Hm. So... we intentionally log you into a new shell I *think* because that is the best way to cd into a new directory. So when I use lambo, I end up within a second shell, and then I have to quit twice instead of once to get out of that session.. but it's not that big of a deal. The weird thing is, for me, that my `$SHELL` is equivalent to the exact same shell I'm using normally so the move into the sub shell is completely invisible to me. I can't figure out why you're not getting the same situation.

BTW, the issue with the "You're ready to go" not showing was an unrelated bug that's fixed in the latestl/

**Comment by jonsugar** [comment]
@nowendwell I'm marking this as won't fix since Lambo is being moved to a PHP implementation. The PHP version is currently in alpha with a beta release coming soon.

**Comment by nowendwell** [comment]
Sounds good!
